# Generated by Django 3.2.16 on 2023-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsanalyzedinternalmodels',
            name='LEMMATIZED_REVIEW',
            field=models.TextField(null=True),
        ),
    ]
