# Generated by Django 3.2.16 on 2023-06-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0002_reviewsanalyzedinternalmodels_lemmatized_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedproductreviews',
            name='ASIN_REVIEW_CONCAT_ID',
            field=models.TextField(null=True, unique=True),
        ),
    ]
