# Generated by Django 3.2.16 on 2023-06-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0004_alter_reviewsanalyzedinternalmodels_processed_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsanalyzedinternalmodels',
            name='PROCESSED_RECORD_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer_insights.processedproductreviews', to_field='RECORD_ID'),
        ),
    ]
