# Generated by Django 3.2.16 on 2023-06-06 15:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0005_alter_reviewsanalyzedinternalmodels_processed_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asins',
            name='MOST_COMMON_WORDS',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='asins',
            name='TOPICS',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
