# Generated by Django 3.2.16 on 2023-06-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0007_alter_asins_most_common_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizedWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WORD', models.TextField()),
                ('CATEGORY', models.TextField()),
            ],
        ),
    ]
