# Generated by Django 3.2.16 on 2023-06-07 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0008_categorizedwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='ASIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_insights.asins', to_field='ASIN'),
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='USER',
            field=models.TextField(),
        ),
    ]
