# Generated by Django 3.2.16 on 2023-06-07 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0009_auto_20230607_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='ASIN',
            field=models.ForeignKey(db_column='ASIN', on_delete=django.db.models.deletion.CASCADE, to='customer_insights.asins', to_field='ASIN'),
        ),
    ]
