# Generated by Django 3.2.16 on 2023-06-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0010_alter_userrequests_asin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedproductreviews',
            name='ASIN_ORIGINAL_ID',
            field=models.ForeignKey(db_column='ASIN_ORIGINAL_ID', on_delete=django.db.models.deletion.CASCADE, to='customer_insights.asins', to_field='ASIN'),
        ),
    ]
