# Generated by Django 3.2.16 on 2023-06-10 16:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0011_alter_processedproductreviews_asin_original_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='ASIN',
            field=models.ForeignKey(db_column='ASIN', on_delete=django.db.models.deletion.CASCADE, to='customer_insights.asins', to_field='ASIN'),
        ),
        migrations.CreateModel(
            name='ProcessedProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COUNTRY', models.TextField()),
                ('TITLE', models.TextField()),
                ('DESCRIPTION', models.TextField()),
                ('FEATURE_BULLETS', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('VARIANTS', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('CATEGORIES', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('URL', models.TextField()),
                ('REVIEWS', models.JSONField()),
                ('ITEM_AVAILABLE', models.BooleanField()),
                ('PRICE', models.JSONField()),
                ('BESTSELLERS_RANK', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('MAIN_IMAGE', models.TextField()),
                ('TOTAL_IMAGES', models.IntegerField()),
                ('IMAGES', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('TOTAL_VIDEOS', models.IntegerField()),
                ('VIDEOS', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('DELIVERY_MESSAGE', models.TextField()),
                ('PRODUCT_INFORMATION', models.JSONField()),
                ('BADGES', models.JSONField()),
                ('SPONSORED_PRODUCTS', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('ALSO_BOUGHT', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('OTHER_SELLERS', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('LOAD_DATE', models.DateTimeField()),
                ('ASIN_ORIGINAL_ID', models.OneToOneField(db_column='ASIN_ORIGINAL_ID', on_delete=django.db.models.deletion.CASCADE, to='customer_insights.asins', to_field='ASIN')),
            ],
        ),
    ]
