# Generated by Django 3.2.16 on 2023-06-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0012_auto_20230610_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.TextField()),
                ('GROUP_NAME', models.TextField()),
                ('ASIN', models.OneToOneField(db_column='ASIN', on_delete=django.db.models.deletion.CASCADE, to='customer_insights.asins', to_field='ASIN')),
            ],
        ),
    ]
