# Generated by Django 3.2.16 on 2023-06-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0013_productgroups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroups',
            old_name='GROUP_NAME',
            new_name='USER_PRODUCT_CATEGORY',
        ),
    ]
