# Generated by Django 3.2.16 on 2023-06-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0014_rename_group_name_productgroups_user_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroups',
            name='ASIN',
            field=models.ForeignKey(db_column='ASIN', on_delete=django.db.models.deletion.CASCADE, to='customer_insights.asins', to_field='ASIN'),
        ),
    ]
