# Generated by Django 3.2.16 on 2023-06-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0015_alter_productgroups_asin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaTesterSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL', models.TextField(unique=True)),
                ('FIRST_NAME', models.TextField()),
            ],
        ),
    ]
