# Generated by Django 3.2.16 on 2023-06-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0016_betatestersignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betatestersignup',
            old_name='FIRST_NAME',
            new_name='NAME',
        ),
    ]
