# Generated by Django 3.2.16 on 2023-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.TextField()),
                ('ASIN', models.TextField()),
                ('COUNTRY', models.TextField()),
                ('SORT_BY', models.TextField()),
                ('PAGE_NUM', models.IntegerField()),
                ('QUERY_DATE', models.DateTimeField()),
                ('RESPONSE', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsAnalyzed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.TextField()),
                ('PROMPT', models.TextField()),
                ('QUERY', models.TextField()),
                ('GPT_RESPONSE', models.TextField()),
                ('COMPLETION_TOKENS', models.IntegerField()),
                ('PROMPT_TOKENS', models.IntegerField()),
                ('QUERY_DATE', models.DateTimeField()),
            ],
        ),
    ]
