# Generated by Django 3.2.16 on 2023-02-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_alter_reviewsanalyzed_gpt_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsanalyzed',
            name='ASIN',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
