# Generated by Django 3.2.16 on 2023-02-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_reviewsanalyzed_asin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.TextField()),
                ('ASIN', models.TextField()),
                ('COUNTRY', models.TextField()),
                ('RESPONSE', models.TextField()),
                ('QUERY_DATE', models.DateTimeField()),
            ],
        ),
    ]
