# Generated by Django 3.2.16 on 2023-03-06 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_processedproductreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsAnalyzedInternalModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.TextField()),
                ('ASIN', models.TextField()),
                ('NOUNS', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('ADJECTIVES', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
