# Generated by Django 3.2.16 on 2023-03-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_reviewsanalyzedinternalmodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsanalyzedinternalmodels',
            old_name='ASIN',
            new_name='REVIEW_ID',
        ),
        migrations.AddField(
            model_name='reviewsanalyzedinternalmodels',
            name='ASIN_ORIGINAL_ID',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reviewsanalyzedinternalmodels',
            name='ASIN_VARIANT_ID',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reviewsanalyzedinternalmodels',
            name='QUERY_DATE',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
