# Generated by Django 3.2.16 on 2023-03-08 03:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_auto_20230306_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedproductreviews',
            name='RECORD_ID',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ReviewsAnalyzedOpenAI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.TextField()),
                ('REVIEW_ID', models.TextField()),
                ('ASIN_ORIGINAL_ID', models.TextField()),
                ('ASIN_VARIANT_ID', models.TextField(null=True)),
                ('PROMPT', models.TextField()),
                ('GPT_RESPONSE', models.JSONField()),
                ('WHO', models.TextField()),
                ('WHERE', models.TextField()),
                ('WHEN', models.TextField()),
                ('DESCRIPTION', models.TextField()),
                ('HOW_OFTEN', models.TextField()),
                ('MOTIVATION', models.TextField()),
                ('EXPECTATIONS', models.TextField()),
                ('COMPLETION_TOKENS', models.IntegerField()),
                ('PROMPT_TOKENS', models.IntegerField()),
                ('QUERY_DATE', models.DateTimeField()),
                ('PROCESSED_RECORD_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.processedproductreviews', to_field='RECORD_ID')),
            ],
        ),
    ]
