# Generated by Django 3.2.16 on 2023-01-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.TextField()),
                ('DOC_TEXT', models.TextField()),
                ('QUERY', models.TextField()),
                ('GPT_RESPONSE', models.TextField()),
                ('COMPLETION_TOKENS', models.IntegerField()),
                ('PROMPT_TOKENS', models.IntegerField()),
                ('QUERY_DATE', models.DateTimeField()),
            ],
        ),
    ]
