# Generated by Django 3.2.16 on 2023-01-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docchatgpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docqueries',
            name='DOC_NAME',
            field=models.TextField(null=True),
        ),
    ]
