# Generated by Django 3.2.16 on 2023-01-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docchatgpt', '0002_docqueries_doc_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.TextField()),
                ('INDEX_NAME', models.TextField()),
                ('QUERY', models.TextField()),
                ('GPT_RESPONSE', models.TextField()),
                ('TOTAL_LLM_TOKEN_USAGE', models.IntegerField()),
                ('TOTAL_EMBEDDING_TOKEN_USAGE', models.IntegerField()),
                ('QUERY_DATE', models.DateTimeField()),
            ],
        ),
    ]
